<?php

namespace App\Livewire\Auth;

use App\Models\Course;
use App\Models\Student;
use App\Models\Supervisor;
use App\Models\User;
use Filament\Forms\Components\Fieldset;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Radio;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\MarkdownEditor;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Illuminate\Contracts\View\View;
use Livewire\Component;

class RegisterUser extends Component implements HasForms
{
    use InteractsWithForms;
    public string $firstname, $middlename, $lastname, $course_id, $major, $section, $student_id, $institutional_email, $address, $student_contact, $guardian_name, $guardian_contact, $password;
    public $contact_no, $company_name, $company_address, $email;

    public $hard_skill = [], $soft_skills = [], $internship_location, $internship_arrangement, $work_experience;

    public $file = [];


    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Fieldset::make('Job requirements')->columns(1)->schema([
                    Select::make('hard_skill')->multiple()->options([
                        'Debugging' => 'Debugging',
                        'Testing' => 'Testing',
                        'Computer programs' => 'Computer programs',
                        'Programming' => 'Programming',
                        'Microsoft Excel' => 'Microsoft Excel',
                        'MS Excel' => 'MS Excel',
                        'Microsoft Office' => 'Microsoft Office',
                        'Software Development' => 'Software Development',
                        'HTML' => 'HTML',
                        'Retention' => 'Retention',
                        'SQL' => 'SQL',
                        'Modeling' => 'Modeling',
                        'Analytics' => 'Analytics',
                        'Apache' => 'Apache',
                        'Apache Airflow' => 'Apache Airflow',
                        'Apache Impala' => 'Apache Impala',
                        'Apache Drill' => 'Apache Drill',
                        'Apache Hadoop' => 'Apache Hadoop',
                        'Data Collection' => 'Data Collection',
                        'Business Requirements' => 'Business Requirements',
                        'Data Mining' => 'Data Mining',
                        'Data Science' => 'Data Science',
                        'Visualization' => 'Visualization',
                        'Technical Guidance' => 'Technical Guidance',
                        'Client Analytics' => 'Client Analytics',
                        'Programming Skills' => 'Programming Skills',
                        'Sql Server' => 'Sql Server',
                        'Computer Science' => 'Computer Science',
                        'Statistical Modeling' => 'Statistical Modeling',
                        'Applied Data Science' => 'Applied Data Science',
                        'Hiring' => 'Hiring',
                        'Technical' => 'Technical',
                        'Database' => 'Database',
                        'R' => 'R',
                        'C' => 'C',
                        'C++' => 'C++',
                        'C#' => 'C#',
                        'Ruby' => 'Ruby',
                        'Ruby on Rails' => 'Ruby on Rails',
                        'Weka' => 'Weka',
                        'Matlab' => 'Matlab',
                        'Django' => 'Django',
                        'NetBeans' => 'NetBeans',
                        'IDE' => 'IDE',
                        'stochastic' => 'stochastic',
                        'Marketing' => 'Marketing',
                        'Mining' => 'Mining',
                        'Mathematics' => 'Mathematics',
                        'Forecasts' => 'Forecasts',
                        'Statistics' => 'Statistics',
                        'Python' => 'Python',
                        'Microsoft Sql Server' => 'Microsoft Sql Server',
                        'NoSql' => 'NoSql',
                        'Hadoop' => 'Hadoop',
                        'Spark' => 'Spark',
                        'Java' => 'Java',
                        'Numpy' => 'Numpy',
                        'Pandas' => 'Pandas',
                        'Scikit' => 'Scikit',
                        'clustering' => 'clustering',
                        'classification' => 'classification',
                        'neural networks' => 'neural networks',
                        'neural network' => 'neural network',
                        'tensorflow' => 'tensorflow',
                        'pytorch' => 'pytorch',
                        'theano' => 'theano',
                        'keras' => 'keras',
                        'Pig' => 'Pig',
                        'Adaboost' => 'Adaboost',
                        'Statistical analysis' => 'Statistical analysis',
                        'machine learning' => 'machine learning',
                        'data mining' => 'data mining',
                        'data science' => 'data science',
                        'data analytics' => 'data analytics',
                        'regression' => 'regression',
                        'kmeans' => 'kmeans',
                        'k-means' => 'k-means',
                        'kNN' => 'kNN',
                        'Bayes' => 'Bayes',
                        'Bayesian Probability' => 'Bayesian Probability',
                        'Bayesian Estimation' => 'Bayesian Estimation',
                        'Bayesian Network' => 'Bayesian Network',
                        'Forest' => 'Forest',
                        'Random Forest' => 'Random Forest',
                        'Decision Tree' => 'Decision Tree',
                        'Matrix' => 'Matrix',
                        'Matrix Factorization' => 'Matrix Factorization',
                        'SVD' => 'SVD',
                        'Outlier' => 'Outlier',
                        'Outlier detection' => 'Outlier detection',
                        'Regression Analysis' => 'Regression Analysis',
                        'Frequent Itemset Mining' => 'Frequent Itemset Mining',
                        'Classification Analysis' => 'Classification Analysis',
                        'Backpropagation' => 'Backpropagation',
                        'LogitBoost' => 'LogitBoost',
                        'Time Series' => 'Time Series',
                        'Dynamic programming' => 'Dynamic programming',
                        'Clustering' => 'Clustering',
                        'Classification' => 'Classification',
                        'Algorithms' => 'Algorithms',
                        'Application Development' => 'Application Development',
                        'AWS' => 'AWS',
                        'AWS Glue' => 'AWS Glue',
                        'Architecture' => 'Architecture',
                        'AROS' => 'AROS',
                        'Ars Based Programming' => 'Ars Based Programming',
                        'Aspect Oriented Programming' => 'Aspect Oriented Programming',
                        'CASE Tools' => 'CASE Tools',
                        'Coding' => 'Coding',
                        'Computer Platforms' => 'Computer Platforms',
                        'Computational complexity' => 'Computational complexity',
                        'Constraint-based Programming' => 'Constraint-based Programming',
                        'Customer Service' => 'Customer Service',
                        'Database Management Systems' => 'Database Management Systems',
                        'Database Techniques' => 'Database Techniques',
                        'Data Analytics' => 'Data Analytics',
                        'Data Structures' => 'Data Structures',
                        'Design' => 'Design',
                        'Design Patterns' => 'Design Patterns',
                        'Development' => 'Development',
                        'Development Tools' => 'Development Tools',
                        'Distributed Computing' => 'Distributed Computing',
                        'Documentation' => 'Documentation',
                        'Embedded Hardware' => 'Embedded Hardware',
                        'Emerging Technologies' => 'Emerging Technologies',
                        'Hardware' => 'Hardware',
                        'HTML Authoring Tools' => 'HTML Authoring Tools',
                        'HTML Conversion Tools' => 'HTML Conversion Tools',
                        'Industry Systems' => 'Industry Systems',
                        'iOS' => 'iOS',
                        'Linux' => 'Linux',
                        'MacOS' => 'MacOS',
                        'Mobile' => 'Mobile',
                        'Multimedia' => 'Multimedia',
                        'MXNet' => 'MXNet',
                        'Object oriented programming' => 'Object oriented programming',
                        'object oriented' => 'object oriented',
                        'Operating Systems' => 'Operating Systems',
                        'Organizational' => 'Organizational',
                        'OS Programming' => 'OS Programming',
                        'Post Object Programming' => 'Post Object Programming',
                        'Presto' => 'Presto',
                        'Problem Solving' => 'Problem Solving',
                        'Programming Languages' => 'Programming Languages',
                        'Programming Methodologies' => 'Programming Methodologies',
                        'Quality Control' => 'Quality Control',
                        'Relational Databases' => 'Relational Databases',
                        'Relational Programming' => 'Relational Programming',
                        'Reporting' => 'Reporting',
                        'Revision Control' => 'Revision Control',
                        'Software' => 'Software',
                        'Structured Query Language (SQL)' => 'Structured Query Language (SQL)',
                        'System Architecture' => 'System Architecture',
                        'System Development' => 'System Development',
                        'System Design' => 'System Design',
                        'System Programming' => 'System Programming',
                        'System Testing' => 'System Testing',
                        'Troubleshooting' => 'Troubleshooting',
                        'UNIX' => 'UNIX',
                        'Web' => 'Web',
                        'Web Applications' => 'Web Applications',
                        'Web Platforms' => 'Web Platforms'
                    ])
                        ->searchable(),
                    Select::make('soft_skills')
                        ->label('Soft Skills')
                        ->multiple()
                        ->searchable()
                        ->options([
                            'abstract thinking' => 'abstract thinking',
                            'accurate' => 'accurate',
                            'achieving goals' => 'achieving goals',
                            'active person' => 'active person',
                            'active personality' => 'active personality',
                            'advocacy skills' => 'advocacy skills',
                            'ambitious' => 'ambitious',
                            'assertive' => 'assertive',
                            'assertiveness' => 'assertiveness',
                            'autonomy' => 'autonomy',
                            'calm' => 'calm',
                            'character' => 'character',
                            'client relationships' => 'client relationships',
                            'coaching' => 'coaching',
                            'conceptual thinking' => 'conceptual thinking',
                            'confident personality' => 'confident personality',
                            'conflict management' => 'conflict management',
                            'curious' => 'curious',
                            'customer orientation' => 'customer orientation',
                            'decision maker' => 'decision maker',
                            'delegation skills' => 'delegation skills',
                            'diplomacy skills' => 'diplomacy skills',
                            'dynamic person' => 'dynamic person',
                            'enthusiastic personality' => 'enthusiastic personality',
                            'hard worker' => 'hard worker',
                            'independent worker' => 'independent worker',
                            'initiative person' => 'initiative person',
                            'innovative thinking' => 'innovative thinking',
                            'judgment skills' => 'judgment skills',
                            'leadership ability' => 'leadership ability',
                            'learn quickly' => 'learn quickly',
                            'learning skills' => 'learning skills',
                            'listening skills' => 'listening skills',
                            'make decisions' => 'make decisions',
                            'memory skills' => 'memory skills',
                            'multitask oriented' => 'multitask oriented',
                            'oral skills' => 'oral skills',
                            'organized person' => 'organized person',
                            'outgoing personality' => 'outgoing personality',
                            'outgoing' => 'outgoing',
                            'people oriented' => 'people oriented',
                            'personal commitment' => 'personal commitment',
                            'personal integrity' => 'personal integrity',
                            'problem solver' => 'problem solver',
                            'problem solving' => 'problem solving',
                            'problemsolving' => 'problemsolving',
                            'professional attitude' => 'professional attitude',
                            'selfconfident' => 'selfconfident',
                            'selflearner' => 'selflearner',
                            'selflearning' => 'selflearning',
                            'sociable personality' => 'sociable personality',
                            'solution oriented' => 'solution oriented',
                            'strategic planning' => 'strategic planning',
                            'supervision skills' => 'supervision skills',
                            'sympathy' => 'sympathy',
                            'systematic' => 'systematic',
                            'team builder' => 'team builder',
                            'teamwork approach' => 'teamwork approach',
                            'teamworker' => 'teamworker',
                            'tolerant' => 'tolerant',
                            'work ethics' => 'work ethics',
                            'polite manners' => 'polite manners',
                            'organizational skills' => 'organizational skills',
                            'work collaboratively' => 'work collaboratively',
                            'communicator' => 'communicator',
                            'accountability' => 'accountability',
                            'mentoring skills' => 'mentoring skills',
                            'communicative' => 'communicative',
                            'reliable personality' => 'reliable personality',
                            'goal oriented' => 'goal oriented',
                            'educational skills' => 'educational skills',
                            'skilled negotiator' => 'skilled negotiator',
                            'monitoring skills' => 'monitoring skills',
                            'reliable' => 'reliable',
                            'sales driven' => 'sales driven',
                            'international outlook' => 'international outlook',
                            'dedicated person' => 'dedicated person',
                            'communicate easily' => 'communicate easily',
                            'discretion' => 'discretion',
                            'relationship builder' => 'relationship builder',
                            'self confidence' => 'self confidence',
                            'self driven' => 'self driven',
                            'imagination' => 'imagination',
                            'organized' => 'organized',
                            'responsible' => 'responsible',
                            'counselling skills' => 'counselling skills',
                            'analytical thinking' => 'analytical thinking',
                            'political awareness' => 'political awareness',
                            'motivation' => 'motivation',
                            'consulting skills' => 'consulting skills',
                            'creativity thinking' => 'creativity thinking',
                            'initiative thinking' => 'initiative thinking',
                            'ingenuity' => 'ingenuity',
                            'versatility' => 'versatility',
                            'leadership' => 'leadership',
                            'positive attitude' => 'positive attitude',
                            'analytic skills' => 'analytic skills',
                            'people skills' => 'people skills',
                            'mature personality' => 'mature personality',
                            'proactive' => 'proactive',
                            'correct reporting' => 'correct reporting',
                            'intercultural skills' => 'intercultural skills',
                            'interpretation skills' => 'interpretation skills',
                            'reporting skills' => 'reporting skills',
                            'self starter' => 'self starter',
                            'timemanagement skills' => 'timemanagement skills',
                            'open minded' => 'open minded',
                            'supervisory skills' => 'supervisory skills',
                            'personable' => 'personable',
                            'self starters' => 'self starters',
                            'presonal initiative' => 'presonal initiative',
                            'self motivated' => 'self motivated',
                            'managing skills' => 'managing skills',
                            'management skill' => 'management skill',
                            'energetic' => 'energetic',
                            'negotiation skills' => 'negotiation skills',
                            'diplomatic manner' => 'diplomatic manner',
                            'judgement skills' => 'judgement skills',
                            'initiative' => 'initiative',
                            'results oriented' => 'results oriented',
                            'telephone skills' => 'telephone skills',
                            'speaking ability' => 'speaking ability',
                            'creative thinking' => 'creative thinking',
                            'team player' => 'team player',
                            'communicating skills' => 'communicating skills',
                            'diplomacy' => 'diplomacy',
                            'communication skill' => 'communication skill',
                            'facilitating skills' => 'facilitating skills',
                            'self organized' => 'self organized',
                            'meeting deadlines' => 'meeting deadlines',
                            'communications skills' => 'communications skills',
                            'analytical skills' => 'analytical skills',
                            'problemsolving attitude' => 'problemsolving attitude',
                            'sensitivity' => 'sensitivity',
                            'personality skills' => 'personality skills',
                            'confident' => 'confident',
                            'attractive personality' => 'attractive personality',
                            'enthusiasm' => 'enthusiasm',
                            'quick learner' => 'quick learner',
                            'work ethic' => 'work ethic',
                            'action oriented' => 'action oriented',
                            'leadership skills' => 'leadership skills',
                            'proactive approach' => 'proactive approach',
                            'time management' => 'time management',
                            'polite' => 'polite',
                            'methodical' => 'methodical',
                            'managing tasks' => 'managing tasks',
                            'results orientation' => 'results orientation',
                            'flexible' => 'flexible',
                            'responsible person' => 'responsible person',
                            'creativity' => 'creativity',
                            'self confident' => 'self confident',
                            'training skills' => 'training skills',
                            'motivated' => 'motivated',
                            'diplomatic' => 'diplomatic',
                            'conceptualization skills' => 'conceptualization skills',
                            'verbal skills' => 'verbal skills',
                            'organizational capabilities' => 'organizational capabilities',
                            'attentive' => 'attentive',
                            'organization skills' => 'organization skills',
                            'courteous manner' => 'courteous manner',
                            'detailed oriented' => 'detailed oriented',
                            'administrative skills' => 'administrative skills',
                            'humor' => 'humor',
                            'flexibility' => 'flexibility',
                            'analysis skills' => 'analysis skills',
                            'teamwork' => 'teamwork',
                            'facilitation skills' => 'facilitation skills',
                            'dynamic personality' => 'dynamic personality',
                            'team oriented' => 'team oriented',
                            'deadline oriented' => 'deadline oriented',
                            'openminded' => 'openminded',
                            'professional manner' => 'professional manner',
                            'professional presentation' => 'professional presentation',
                            'analytical mind' => 'analytical mind',
                            'cheerful personality' => 'cheerful personality',
                            'critical thinking' => 'critical thinking',
                            'hard working' => 'hard working',
                            'self initiative' => 'self initiative',
                            'take initiative' => 'take initiative',
                            'result oriented' => 'result oriented',
                            'innovative' => 'innovative',
                            'organizing skills' => 'organizing skills',
                            'interpersonal skills' => 'interpersonal skills',
                            'self awareness' => 'self awareness',
                            'team commitment' => 'team commitment',
                            'presentation skills' => 'presentation skills',
                            'systematic manner' => 'systematic manner',
                            'cooperation skills' => 'cooperation skills',
                            'client oriented' => 'client oriented',
                            'client orientation' => 'client orientation',
                            'self motivation' => 'self motivation',
                            'creative' => 'creative',
                            'results driven' => 'results driven',
                            'positive' => 'positive',
                            'tactful manner' => 'tactful manner',
                            'coordination skills' => 'coordination skills',
                            'tactful' => 'tactful',
                            'responsible personality' => 'responsible personality',
                            'reasoning skills' => 'reasoning skills',
                            'team worker' => 'team worker',
                            'dedication' => 'dedication',
                            'sound judgment' => 'sound judgment',
                            'goals oriented' => 'goals oriented',
                            'organisational skills' => 'organisational skills',
                            'marketing skills' => 'marketing skills',
                            'managerial ability' => 'managerial ability',
                            'professionalism' => 'professionalism',
                            'problemsolving skills' => 'problemsolving skills',
                            'detail oriented' => 'detail oriented',
                            'influencing skills' => 'influencing skills',
                            'teambuilding skills' => 'teambuilding skills',
                            'courteous' => 'courteous',
                            'client skills' => 'client skills',
                            'innovativeness' => 'innovativeness',
                            'wellorganized' => 'wellorganized',
                            'creative imagination' => 'creative imagination',
                            'listen skills' => 'listen skills',
                            'analytical abilities' => 'analytical abilities',
                            'logical abilities' => 'logical abilities',
                            'maturity' => 'maturity',
                            'social skills' => 'social skills',
                            'respectful' => 'respectful',
                            'teamwork skills' => 'teamwork skills',
                            'punctual' => 'punctual',
                            'managerial skills' => 'managerial skills',
                            'management skills' => 'management skills',
                            'accuracy' => 'accuracy',
                            'scheduling skills' => 'scheduling skills',
                            'constructive feedback' => 'constructive feedback',
                            'well organized' => 'well organized',
                            'conceptual skills' => 'conceptual skills',
                            'hardworking' => 'hardworking',
                            'empathy' => 'empathy',
                            'ambitious personality' => 'ambitious personality',
                            'lively personality' => 'lively personality',
                            'punctuality' => 'punctuality',
                            'creative approach' => 'creative approach',
                            'organizer' => 'organizer',
                            'self directed' => 'self directed',
                            'initiative driven' => 'initiative driven',
                            'goaloriented' => 'goaloriented',
                            'cultural sensitivity' => 'cultural sensitivity',
                            'friendly personality' => 'friendly personality',
                            'responsable' => 'responsable',
                            'patience' => 'patience',
                            'communication skills' => 'communication skills',
                            'enthusiastic' => 'enthusiastic',
                            'judgment' => 'judgment',
                            'coordinating skills' => 'coordinating skills',
                            'motivating' => 'motivating',
                            'disciplined' => 'disciplined',
                            'articulate' => 'articulate',
                            'organising skills' => 'organising skills',
                            'responsibility' => 'responsibility',
                            'team spirit' => 'team spirit',
                            'planning skills' => 'planning skills',
                            'coaching skills' => 'coaching skills',
                            'tact' => 'tact',
                            'diligent' => 'diligent',
                            'hardworker' => 'hardworker',
                            'service mentality' => 'service mentality',
                            'prioritization skills' => 'prioritization skills',
                            'negotiator' => 'negotiator',
                            'communication abilities' => 'communication abilities',
                            'professional personality' => 'professional personality',
                            'strategic thinking' => 'strategic thinking',
                            'quality minded' => 'quality minded',
                            'public speaking' => 'public speaking',
                            'self learning' => 'self learning',
                            'forward thinker' => 'forward thinker',
                            'team management' => 'team management',
                            'personal management' => 'personal management',
                            'staff management' => 'staff management',
                            'people management' => 'people management',
                            'project management' => 'project management',
                            'be creative' => 'be creative',
                            'multitasking skills' => 'multitasking skills',
                            'quick learning' => 'quick learning',
                            'proposal writing' => 'proposal writing',
                        ])
                        ->searchable()
                ]),
                Grid::make(2)->schema([
                    Radio::make('work_experience')
                        ->label('Work Experience Required?')
                        ->options([
                            'yes' => 'yes',
                            'no' => 'no',
                        ])->inline()
                        ->inlineLabel(false),
                    Radio::make('internship_location')
                        ->label('Internship Location')
                        ->options([
                            'LSPU' => 'LSPU',
                            'outside' => 'outside',
                        ])->inline()
                        ->inlineLabel(false),
                ]),
                Radio::make('internship_arrangement')
                    ->label('Internship Arrangement')
                    ->options([
                        'On-site' => 'On-site',
                        'Remote' => 'Remote',
                        'Hybrid' => 'Hybrid',
                    ])->inline()
                    ->inlineLabel(false),
            ]);
    }

    public function render()
    {
        return view('livewire.auth.register-user', [
            'courses' => Course::all(),
        ]);
    }

    protected $rules = [
        'firstname' => 'required',
    ];


    public function registerStudent()
    {


        $this->validate();

        $this->validate([
            'firstname' => 'required',
            'middlename' => 'required',
            'lastname' => 'required',
            'course_id' => 'required',
            'major' => 'required',
            'section' => 'required',
            'student_id' => 'required',
            'institutional_email' => 'required|email',
            'address' => 'required',
            'student_contact' => 'required',
            'guardian_name' => 'required',
            'guardian_contact' => 'required',
            'password' => 'required|min:8',
        ]);




        $user = User::create([
            'name' => $this->firstname . ' ' . $this->lastname,
            'email' => $this->institutional_email,
            'password' => bcrypt($this->password),
            'user_type' => 'student',
            'course_id' => $this->course_id,
        ]);

        Student::create([
            'user_id' => $user->id,
            'firstname' => $this->firstname,
            'middlename' => $this->middlename,
            'lastname' => $this->lastname,
            'major' => $this->major,
            'section' => $this->section,
            'course_id' => $this->course_id,
            'student_id' => $this->student_id,
            'address' => $this->address,
            'student_contact' => $this->student_contact,
            'guardian_name' => $this->guardian_name,
            'guardian_contact' => $this->guardian_contact,
        ]);

        auth()->loginUsingId($user->id);
        sleep(4);

        return redirect()->route('dashboard');
    }

    public function registerSupervisor()
    {

        $this->validate([
            'firstname' => 'required',
            'lastname' => 'required',
            'company_name' => 'required',
            'company_address' => 'required',
            'contact_no' => 'required',
            'email' => 'required|email',
            'password' => 'required|min:8',
        ]);


        $user = User::create([
            'name' => $this->firstname . ' ' . $this->lastname,
            'email' => $this->email,
            'password' => bcrypt($this->password),
            'user_type' => 'supervisor',
        ]);

        $data = [
            'hardskill' => $this->hard_skill,
            'softskill' => $this->soft_skills,
            'work_experience' => $this->work_experience,
            'internship_location' => $this->internship_location,
            'internship_arrangement' => $this->internship_arrangement,
        ];


        $super = Supervisor::create([
            'user_id' => $user->id,
            'firstname' => $this->firstname,
            'lastname' => $this->lastname,
            'middlename' => $this->middlename,
            'company_name' => $this->company_name,
            'company_address' => $this->company_address,
            'contact_number' => $this->contact_no,
            'job_requirements' => json_encode($data),
        ]);

        foreach ($this->file as $key => $value) {
            $super->update([
                'location_path' => $value->store('supervisor', 'public'),
            ]);
        }

        auth()->loginUsingId($user->id);
        sleep(4);

        return redirect()->route('dashboard');
    }
}
